### PR TITLE
Implement server regions

### LINKED ISSUE #2: Add geo info to server list
Continued from R2Northstar/NorthstarMasterServer#84.

### PR DESCRIPTION
**Pull request by pg9182**
closes #2
closes R2Northstar/NorthstarMasterServer#84

### CODE REVIEW

**Review by pg9182 — COMMENTED** [review]
With the current server list, this results in the following regions:

```
      1 Americas
      2 Asia East
      2 Canada East
      3 Europe East
      5 US Central
      7 Australia
      7 US East
     11 US West
     24 US South
     25 Europe North
     42 Europe West
```

**Comment by pg9182** [comment]
Questions for reviewers:
- Do we want to add additional "well-known" region names for specific countries?
- Thoughts on my current mapping?

**Comment by pg9182** [comment]
@GeckoEidechse, regarding R2Northstar/NorthstarLauncher#232, the `region` field in the server list will either be a non-empty string, or it will not be present (and should be displayed as an empty string).

**Comment by GeckoEidechse** [comment]
> With the current server list, this results in the following regions:
> 
> ```
>       1 Americas
>       2 Asia East
>       2 Canada East
>       3 Europe East
>       5 US Central
>       7 Australia
>       7 US East
>      11 US West
>      24 US South
>      25 Europe North
>      42 Europe West
> ```

From experience playing the game, there's barely a ping difference between `Europe North` and Europe `West`. Similarly, where does `Europe East` begin? Cause everything West of Moscow still gets decent ping to most of Europe including London. So everything in that area could also be absolved into `Europe`.

Given that we don't have a way to sort server browser based on players' on distance to a region but solely alphabetically based on the region name, it makes more sense to go more coarse grained, such that everything within `+/-20ms` of each other is in the same "region".
As an example from a player's perspective: Living in central Europe, I do not care whether the server is in Frankfurt (:de:), Helsinki (:finland:), London (:gb:), or Moscow (:ru:). The latency for me is decent enough to all of them. As such, with a secondary filter on playercount, having all these regions in `Europe` means I don't have waste as much time finding the first location where I get decent ping to that also has players on the server.

**Review by GeckoEidechse — COMMENTED** [review]
Cannot comment on the code as I've never written a single line of Go so far. As for reaching mapping, see https://github.com/R2Northstar/Atlas/pull/12#issuecomment-1321095516

**Comment by pg9182** [comment]
Different areas of Europe have a noticeable difference from NA.

**Comment by pg9182** [comment]
Also, I recommend sorting by count > 0, before region, then count.

**Comment by Alystrasz** [comment]
> With the current server list, this results in the following regions:
>
>      1 Americas
>      2 Asia East
>      2 Canada East
>      3 Europe East
>      5 US Central
>      7 Australia
>      7 US East
>     11 US West
>     24 US South
>     25 Europe North
>     42 Europe West

I suppose you made this list from this servers map? (https://github.com/R2Northstar/Atlas/issues/2#issuecomment-1321015849)

image

I'd argue some regions are missing / aren't accurate enough. We can't do a mapping entirely based on stats, that would impact future servers in currently missing regions. 

A good example is servers located in Asia, I suppose you don't have them displayed on your map because they don't use same master server (@wolf109909 can you confirm?).

**Comment by pg9182** [comment]
@Alystrasz 

The list came from atlas on `northstar.tf`. It isn't exactly what's on the map (the map includes the last 24h rather than just the current instant).

If you want to see all the possible regions, they're here: https://github.com/R2Northstar/Atlas/blob/b3d1c42cf268153831494e8b7b854c621f015497/pkg/regionmap/region.go#L24-L167.

**Pull request merged**
